### ISSUE TITLE
How to use notify property in MyCallbackHandler : public BLECharacteristicCallbacks function for Wifi UUID

### ISSUE THREAD

**Issue by IoTopsDeveloper** [beegee-tokyo/ESP32WiFiBLE-NimBLE#1]
Hey Beegee I found this code very useful and I am working on it, its quite best code with the app my-nRF52-Toolbox
From my side, I want to add Notify Property in Wifi UUID in the callback function class
` MyCallbackHandler : public BLECharacteristicCallbacks` if wrong Wifi Credentials are put in Send Config Button.
and instead of getting Wifi Credentials in the function `void onRead(BLECharacteristic *pCharacteristic)` I want to get scanned available networks with SSID and RSSI in Json Format. Would you please guide me it will be amazing

**Comment by beegee-tokyo** [comment]
Hi,
I am not an expert in BLE, but here is the idea how it might work
1) when creating the wifi characteristic you will have to add the `NIMBLE_PROPERTY::NOTIFY` flag in addition to `NIMBLE_PROPERTY::READ` and `NIMBLE_PROPERTY::WRITE`
2) in the callbacks you add a `void onNotify(BLECharacteristic *pCharacteristic)` and add what ever you want to do on a notifcation
3) in the Android app you will have to add a `void notifySettings(final String parameter)` function in the ESP32Manager.java class. Then you can send a notification to the device with `getService().sendNotification(new String(decodedData));`

All of above is just my guess. Let me know if it works for you.

**Comment by IoTopsDeveloper** [comment]
Actually I done something else : 
- For Notification purpose I have set another UUID only for notifications
- Instead of using `void onNotify(BLECharacteristic *pCharacteristic)` I am using `pCharacterstic->setValue("String");` and `pCharacterstic->notify();` in `loop()` and it actually worked. 

Thank You for the guidance in this , the code is really good and helping me in my project
Kudos and Cheers!

**Comment by IoTopsDeveloper** [comment]
Hey @beegee-tokyo , I will need your help for the following code linked [BLE OTA via Arduino](https://github.com/fbiego/ESP32_BLE_OTA_Arduino) to integrate with your Wifi Configure via BLE, I want to add Device Firmware Upgrade via BLE with your code but it couldn't getting it .
Is there any way for the ESP32 Device Firmware Upgrade through BLE in Arduino Sketch via Nordic Toolkit DFU Function as this you added in your App ?

**Comment by beegee-tokyo** [comment]
Should be straight forward by adding the characteristic and callbacks from fbiegos code. 
I am not aware of any example that would show how to update the ESP32 with the Nordic Tookit or nRFConnect.

**Comment by IoTopsDeveloper** [comment]
Honestly I tried best to integrate it with your code but OTA part is not executed due to Wifi Functions running in main loop 
Actually I have integrated this  [BLE OTA via Arduino](https://github.com/fbiego/ESP32_BLE_OTA_Arduino) with your [previous code](https://desire.giesecke.tk/index.php/2018/04/06/esp32-wifi-setup-over-ble/) with [customized partition](https://desire.giesecke.tk/index.php/2018/04/20/change-partition-size-arduino-ide/) but it failed.
I am attaching the code I tried this
[Smart_Automation.zip](https://github.com/beegee-tokyo/ESP32WiFiBLE-NimBLE/files/6680672/Smart_Automation.zip)

**Comment by beegee-tokyo** [comment]
I had a look into your code and I do not understand what you mean with `OTA part is not executed due to Wifi Functions`.
You switch depending on `MODE` and once the OTA is started, it should not do any work with your MQTT connection.
Can you try to stop the MQTT Client when an BLE OTA starts.

Other than that I don't know why it fails. And I am sorry, but I do not have the time right now to look deeper into your problem.

**Comment by IoTopsDeveloper** [comment]
Actually I dont know how to stop MQTT client to start BLE OTA, may be it can be done by adding Free RTOS Task Function but I didn't know RTOS , may be you can help me by integrating [BLE via OTA](https://github.com/fbiego/ESP32_BLE_OTA_Arduino) in this sketch 
[SmartAutomation.zip](https://github.com/beegee-tokyo/ESP32WiFiBLE-NimBLE/files/6720237/SmartAutomation.zip)
He has BLE OTA Application in his [Repo](https://github.com/fbiego/ESP32_BLE_OTA_Arduino) .

**Comment by beegee-tokyo** [comment]
I am very busy these days.

Did you try to disconnect with `mqttClient.disconnect()` when the OTA starts?

**Comment by IoTopsDeveloper** [comment]
Hey @beegee-tokyo Would you check-out this addition in[ Firmware Update OTA via BLE](https://github.com/fbiego/ESP32_BLE_OTA_Arduino/tree/main/esp32_nim_ble_ota) , he had done this in[ NimBLE ](https://github.com/h2zero/NimBLE-Arduino)librabry , You should try this to add it on your [WiFi Configuration code](https://github.com/beegee-tokyo/ESP32WiFiBLE-NimBLE).
