### ISSUE TITLE
Couldn't connect it with AWS IoT MQTT with WiFiClientSecure in ArduinoIDE

### ISSUE THREAD

**Issue by ashish-iottive** [beegee-tokyo/ESP32WiFiBLE-NimBLE#2]
Hey @beegee-tokyo I have used your code and integrated with unsecured MQTT Broker and it worked successfully , but when I used it to connect it with AWS IoT Core (MQTT with SSL) using WiFiClientSecure , it doesn't connected used both codes (with this NimBLE and [ESP32 WiFi setup over BLE (ESP32 code)](https://desire.giesecke.tk/index.php/2018/04/06/esp32-wifi-setup-over-ble/)].
Is the BLE feature through which MQTT(with SSL) is not working or is there anything another.
Need some guidance.
[NimBle-WiFi-AWS.zip](https://github.com/beegee-tokyo/ESP32WiFiBLE-NimBLE/files/7066334/NimBle-WiFi-AWS.zip)
[Nimble-WiFi-AWS-Spiffs.zip](https://github.com/beegee-tokyo/ESP32WiFiBLE-NimBLE/files/7066335/Nimble-WiFi-AWS-Spiffs.zip)

**Comment by beegee-tokyo** [comment]
Hello @ashish-iottive 
I am sorry, but my example has nothing to do with MQTT connections. And I would like to help, but I really do not have much spare time right now.

**Comment by ashish-iottive** [comment]
No Problem @beegee-tokyo is there any other example which implement BluFi concept in Arduino for ESP32 through which WiFi configured via BLE after configured which connect via WiFi that can access MQTT with or without SSL

**Comment by beegee-tokyo** [comment]
Quick Google search find this: https://robotzero.one/esp32-wi-fi-connection-bluetooth/

**Comment by ashish-iottive** [comment]
Ok I found the solution in this[ Issue](https://github.com/chegewara/esp32-snippets/issues/2#issuecomment-405275150) and its Working Properly with MQTT with SSL using `WiFiClientSecure`. Thank You @beegee-tokyo  for giving valuable time although solution has been found. Apologies if any inconvenience caused.
 You may delete this issue if it is causing any trouble in this repo.
